### PR TITLE
Support CMake builds

### PR DESCRIPTION
**Pull request by grisumbras**

### CODE REVIEW

**Comment by vinniefalco** [comment]
Are you serious? We need these dependencies?
```
        assert
        config
        core
        optional
        smart_ptr
        static_assert
        system
        throw_exception
        utility

        # indirect dependencies
        container_hash
        detail
        integer
        io
        move
        predef
        preprocessor
        type_traits
        winapi
```

How did this happen

**Comment by grisumbras** [comment]
```shell
$ ag 'include\s+<boost' -C0 --nofilename include | sed -n 's|.*boost/\(\w\+\)[/>\.].*|\1|p' | sort | uniq                                                                       
assert
config
core
make_unique
optional
static_assert
system
throw_exception
type_traits
utility
zlib
```
These are all direct dependencies (make_unique comes from smart_ptr).

**Comment by vinniefalco** [comment]
Can you please add a commit that replaces `make_unique` with a simple `new` construction? And see if that gets rid of all those annoying dependencies?

**Comment by grisumbras** [comment]
Moved the PR to CPPAlliance/Zlib

**Pull request closed without merging**
